version: '3'
services:
  influxdb:
    image: influxdb 
    ports:
      - "8086:8086"
    networks:
      - iot-network
  broker:
    image: eclipse-mosquitto
    networks:
      - iot-network
    ports:
      - "1883:1883"
      - "9001:9001"
  graphing:
    image: grafana/grafana
    ports: 
      - "3000:3000"
    networks:
      - iot-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/grafana.conf:/etc/nginx/conf.d/grafana.conf
    networks:
      - iot-network
    depends_on:
      - graphing
networks:
  iot-network:
    driver: bridge
