---

- name: Update and Upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

  # Download Grafana
- name: Download Grafana
  package:
    deb: https://dl.grafana.com/oss/release/grafana_5.4.2_amd64.deb

# Installing required packages
- name: Install libfontconfig
  package:
    name: libfontconfig
    state: installed

- name: Install adduser
  package:
    name: adduser
    state: installed

- name: Install nginx
  package:
    name: nginx
    state: installed

# Changing configuation file to send http traffic
# to port 3000
- name: Change configuation file
  copy:
    src: ../templates/grafana.conf
    dest: /etc/nginx/conf.d/grafana.conf

- name: Start Grafana
  service:
    name: grafana-server
    state: started

- name: Restart nginx
  service:
    name: nginx
    state: restarted
